//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP_2
{
    using Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Contrat
    {
        [DisplayName("Type de travailleur")]
        public decimal idContrat { get; set; }
        [DisplayName("Date d'entrée")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public System.DateTime dateEntree { get; set; }
        public decimal idTravailleur { get; set; }
        public decimal numero { get; set; }
        [DisplayName("Date de sortie")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> dateSortie { get; set; }
        public string codeAlphabetique { get; set; }
    
        public virtual EntrepriseClient EntrepriseClient { get; set; }
        public virtual ContratTravailleurNonSoumis ContratTravailleurNonSoumis { get; set; }
        public virtual ContratTravailleurSoumis ContratTravailleurSoumis { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Travailleur Travailleur { get; set; }
    }
}
