//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIG3B7Entities : DbContext
    {
        public DBIG3B7Entities()
            : base("name=DBIG3B7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<ContratTravailleurNonSoumis> ContratTravailleurNonSoumis { get; set; }
        public virtual DbSet<ContratTravailleurSoumis> ContratTravailleurSoumis { get; set; }
        public virtual DbSet<EntrepriseClient> EntrepriseClient { get; set; }
        public virtual DbSet<Interlocuteur> Interlocuteur { get; set; }
        public virtual DbSet<Langue> Langue { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<TraductionEntreprise> TraductionEntreprise { get; set; }
        public virtual DbSet<TraductionProfession> TraductionProfession { get; set; }
        public virtual DbSet<Travailleur> Travailleur { get; set; }
    }
}
